language: python
python:
- '2.7'
install:
- pip install coveralls
script:
- coverage run --source=postcodepy setup.py test
after_success:
- coveralls
env:
  global:
  - secure: YNojZicdzOLWvsa0ebtmbM+PnkcYavr6XM/0aQtLSMCQG33vVGJsE8FLzSUYQ55zPsgUfBeqvIyuEh7cxNE4ldeOwymJsuwZwoDDw9hkf4/jA0DCSzDpPzGe7qDV/8yhrU50o4CpK8qofBBuypYT5pwuolNHY4Cz06KLEG9SMreq01O4jl7Xv39kxi+F58d7XqOyKDvJ0dT6tRIZ0/M4wkgUTC7u71zjnHKwT4IwlM1lhkobZgBMVjRpJGQB7gsXg5cLFEsW6Qm+1kcNqzHU/8vJiI7qxWHP+lvvwwaoH3v5g9hUdsel72YodfxbDRUjFFFOJZWZuzB3TzZCOzD4pgofJcBSfAFws73B53ylVeQaWvVaRL7YbPRGh9xka0Qp1PjWMbEKpVJutrxBEi3N1sUH6AmVHuUmVtbhjSNSKctZBKkPNtfMSCyt/uDKtGPQjKwxQYvLCDvIyQrgxhpbmQzWY1efnaCkCedor8oIOBSov6VpExUS7O95BtQr2YbTqnP6USXf6lamqc7Jzlz2rDMEyF9aNH0DqdSld2rrsmV9sI4GFmolpnTISmZYJahxPHAxAo4rcgih2BJFDCGGnFoJ0RePPF+Vw4/fwkG2VMgsuS2YwtOLIrOI7EQX90XS6FaKo/GO/HuWv7HhzPGkdoSKCPyu+EYb9jLuLCsjBNM=
  - secure: tw/2kX18S40blb/DvnXw8wxLiuIiX/52+osPjSyiptRVeFG8id8MuI18ecrp5EyQ+fZiceJA8FQghnrV5scSZ5g18vQecs1+mqmyEr7FFMjalzPETJ3Bkr2jgIvYH5XSJu2NOK91ys1tdR33ZNqt5nLNk8GT1MQZnw7jENKEuW+qUTIfDGPx6m8v5FK7Jzi0MN+r9NMgaDSl0C7eQjE7MzNKEKFf8pcPx/KZMeyR/Ynx/NtS6hN2WBgKZbcxJRTVMzCMH5J2UmrhtaP2tsB/31Hz5tPnV2vl7KcNPAnL4Hd1Twsi5ZjvMnk5sGkMtMEil6kgVE1fh+TOH9HquAQXb43CMfG4zzE58A1uidraWiZ9s3oJjp4cEh5jUwY+GfLgXl3Wv8MMPUR9AzhU5IYtLxjAO7WGW5C9gMZoOUnQ7swx5XOv/aLXWMHTElJWMsdI0lh2FHUOs3mgDUEZAZdmYTN19nuixJUD6vwOQ6g7tmtqmdh7C9How0/zZ7hmNwxQcvISVOU4Eizll09emnQSDRKeXc527JWbjuKmEHKIb1lrpkVAfwGR2JSVOIZjt1/y3uxp4Vnb/pwIZjGCdaKt4XibJAl4eJImoit7XM4/nGD8xYVnl0Rcec1WWakR0AEitrMgbl9KhKjMC7VYWfyHqpoOuQ/qN/JPsS3Gm+3kNjA=
